#!/bin/bash
# CMMS Manual Testing Script
# This script provides step-by-step manual testing procedures for the CMMS module

echo "==================================="
echo "CMMS Module Manual Testing Guide"
echo "==================================="
echo ""

echo "Prerequisites:"
echo "1. Express server running on port 5000"
echo "2. Laravel API running on port 8001"
echo "3. Database seeded with test data"
echo "4. Logged in as user with CMMS permissions"
echo ""

echo "--- Test 1: CMMS Navigation ---"
echo "Steps:"
echo "1. Navigate to /cmms"
echo "2. Verify redirect to /cmms/dashboard"
echo "3. Check sidebar shows: Dashboard, Assets, Work Orders, Parts Inventory, Asset Map"
echo "4. Click each menu item and verify page loads"
echo "Expected: All menu items accessible, no errors"
echo ""

echo "--- Test 2: Assets List Page ---"
echo "Steps:"
echo "1. Navigate to /cmms/assets"
echo "2. Verify assets table displays with columns: Code, Name, Class, Status, etc."
echo "3. Click 'Add Asset' button"
echo "4. Verify AssetFormDialog opens"
echo "5. Fill required fields: code, name, class"
echo "6. Submit form"
echo "Expected: New asset created, toast notification shown, table updates"
echo ""

echo "--- Test 3: Asset Edit ---"
echo "Steps:"
echo "1. On assets list, click Edit button on any asset"
echo "2. Verify form pre-fills with asset data"
echo "3. Modify name field"
echo "4. Submit form"
echo "Expected: Asset updated, toast shown, changes reflected in list"
echo ""

echo "--- Test 4: Asset Detail Page ---"
echo "Steps:"
echo "1. Click on any asset in the list"
echo "2. Verify detail page shows asset information"
echo "3. Check 'Work Orders' section displays related WOs"
echo "4. Verify Quick Stats shows correct counts"
echo "Expected: All asset data displayed, work orders table populated if WOs exist"
echo ""

echo "--- Test 5: Work Orders Page ---"
echo "Steps:"
echo "1. Navigate to /cmms/work-orders"
echo "2. Verify work orders table displays"
echo "3. Click 'Create Work Order' button"
echo "4. Fill form: title, kind, priority, asset"
echo "5. Optionally assign to user"
echo "6. Submit form"
echo "Expected: New work order created, appears in list"
echo ""

echo "--- Test 6: Work Order Assignment ---"
echo "Steps:"
echo "1. Create or edit a work order"
echo "2. In 'Assigned To' dropdown, select a user"
echo "3. Submit form"
echo "4. Verify work order shows assigned user"
echo "Expected: Assignment saved correctly"
echo ""

echo "--- Test 7: Parts Inventory Page ---"
echo "Steps:"
echo "1. Navigate to /cmms/parts"
echo "2. Verify parts table displays with stock levels"
echo "3. Check low stock items show orange indicators"
echo "4. Check out of stock items show red badges"
echo "5. Click 'Add Part' button"
echo "6. Fill form: code, name, category, unit"
echo "7. Set reorder level and unit cost"
echo "8. Submit form"
echo "Expected: New part created, stock indicators correct"
echo ""

echo "--- Test 8: Asset Map Page ---"
echo "Steps:"
echo "1. Navigate to /cmms/map"
echo "2. Verify MapLibre GL map loads"
echo "3. Verify asset markers appear (colored by status)"
echo "4. Click on an asset marker"
echo "5. Verify popup shows asset details"
echo "6. Click 'View Details' in popup"
echo "Expected: Map loads, markers clickable, navigation works"
echo ""

echo "--- Test 9: RBAC - View Only User ---"
echo "Steps:"
echo "1. Login as user with only 'view assets' permission"
echo "2. Navigate to /cmms"
echo "3. Verify 'Add Asset' button is hidden"
echo "4. Verify Edit buttons are hidden"
echo "5. Try to access /cmms/work-orders"
echo "Expected: Create/Edit actions hidden, unauthorized routes blocked"
echo ""

echo "--- Test 10: RBAC - Full Permissions User ---"
echo "Steps:"
echo "1. Login as user with all CMMS permissions"
echo "2. Navigate to /cmms"
echo "3. Verify all menu items visible"
echo "4. Verify Add/Edit/Delete buttons visible"
echo "Expected: Full access to all features"
echo ""

echo "--- Test 11: Filtering and Search ---"
echo "Steps:"
echo "1. On /cmms/assets, use search box"
echo "2. Enter asset code or name"
echo "3. Verify results filter correctly"
echo "4. Use status filter dropdown"
echo "5. Verify filtered results"
echo "Expected: Filters work correctly, results update"
echo ""

echo "--- Test 12: Pagination ---"
echo "Steps:"
echo "1. On any list page with >15 items"
echo "2. Verify pagination controls appear"
echo "3. Click 'Next' button"
echo "4. Verify page 2 loads"
echo "5. Verify item counts correct"
echo "Expected: Pagination works, counts accurate"
echo ""

echo "--- Test 13: Form Validation ---"
echo "Steps:"
echo "1. Open any create form"
echo "2. Submit without filling required fields"
echo "3. Verify validation errors appear"
echo "4. Fill invalid data (e.g., negative numbers)"
echo "5. Verify validation catches errors"
echo "Expected: All validation rules enforced"
echo ""

echo "--- Test 14: Error Handling ---"
echo "Steps:"
echo "1. Stop Laravel API server"
echo "2. Try to load assets page"
echo "3. Verify error message displays"
echo "4. Restart Laravel API"
echo "5. Refresh page"
echo "Expected: Graceful error handling, recovery when API returns"
echo ""

echo "--- Test 15: End-to-End Workflow ---"
echo "Steps:"
echo "1. Create a new asset"
echo "2. Navigate to asset detail page"
echo "3. From detail page, create work order for asset"
echo "4. Verify work order appears in asset's WO list"
echo "5. Edit work order status to 'in_progress'"
echo "6. Verify status updates everywhere"
echo "Expected: Full workflow works smoothly"
echo ""

echo "==================================="
echo "Testing Complete!"
echo "==================================="
echo "Report any failures with:"
echo "- URL where issue occurred"
echo "- User permissions"
echo "- Expected vs actual behavior"
echo "- Browser console errors"
